### ISSUE TITLE
Add artifact to deploy apps via the Appsody Application Operator

### ISSUE THREAD

**Issue by arthurdm** [appsody/stacks#171]
Each Stack needs an `app-deploy.yaml` file that represents the minimal set of configuration needed to deploy the application image.

```yaml
apiVersion: appsody.dev/v1alpha1
kind: AppsodyApplication
metadata:
  name: REPLACE-NAME
spec:
  applicationImage: REPLACE-IMAGE
  stack: java-microprofile
```

The field `REPLACE-NAME` should be modified to match the service's name (must be unique), and `REPLACE-IMAGE` should be modified to represent the full image path, such as `registry/imageName:imageTag`.

**Comment by arthurdm** [comment]
Here's a more complex example, demonstrating a lot of the other fields for completeness:

```yaml
apiVersion: appsody.dev/v1alpha1
kind: AppsodyApplication
metadata:
  name: demo-appsodyapplication
spec:
  applicationImage: docker-registry.default.svc:5000/demo/appsody-app:1.0.0
  stack: java-microprofile
  env:
    - name: "dbUrl"
      value: "http://couchdb-svc-couchdb:5984"
    - name: dbUsername
      valueFrom:
        secretKeyRef:
          name: couchdb-couchdb
          key: adminUsername
    - name: dbPassword
      valueFrom:
        secretKeyRef:
          name: couchdb-couchdb
          key: adminPassword
  architecture:
    - amd64
  expose: true
  resourceConstraints:
    limits:
      memory: 512Mi
      cpu: 2
    requests:
      cpu: 0.5
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /health
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
  service:
    port: 9080
    type: ClusterIP
```
