### ISSUE TITLE
Allow templates to be included inside the stack image

### ISSUE THREAD

**Issue by ebullient** [appsody/stacks#181]
**Is your feature request related to a problem? Please describe.**

As stacks are customized and distributed, it becomes increasingly likely that templates and stacks will get out of sync (since they are published as separate artifacts). Templates are comparatively thin, but often depend on the build behavior of the stack (at least in a "this template requires this minimum version of the stack" sense).

**Describe the solution you'd like**

I think the templates should be packaged inside the stack. That way, you can extract/use a template from any stack image, and you never get into the situation where a project can't be created because either the two separate publishing mechanisms are out of sync.

From an `index.yaml` POV, this could look something like this: 
```
  - id: java-spring-boot2
    name: Spring Boot®
    version: 0.4.0
    description: Spring Boot using OpenJ9 and Maven
    license: Apache-2.0
    maintainers:
      - name: Erin Schnabel
        email: schnabel@us.ibm.com
        github-id: ebullient
    default-template: default
    templates:
      - id: default
        url: image:/templates/default.tgz
      - id: kotlin
        url: image:/templates/kotlin.tgz
    image: appsody/java-spring-boot2:0.4.0
```

If the `image:` URL is present, then the `image` tag is used  to find the templates (this assumes one image per appsody stack).

The side effect of this is that, during build/packaging, I can take parameters like the git organization and repo, and the version from the stack.yaml and propagate those down through the templates in one shot, reducing the number of resources that need to be updated as things are forked or cloned.
