### ISSUE TITLE
Define release process and create relevant documentation

### ISSUE THREAD

**Issue by tomleah** [appsody/stacks#46]
### Info about a stack
- Stack providers will provide this information using `stack.yaml`
- Proposed format:
```
name: Java MicroProfile® (title on website)
version: 0.2.2
description: Eclipse MicroProfile using AdoptOpenJDK and Maven (description on website)
license: Apache-2.0
maintainers: 
- name:
  email:
  github-id:                  
default-template: <folder-name>
```
- Version should be captured using <major>.<minor>.<patch> format
- Every time a stack image or template is updated the version in `stack.yaml` must be updated
- When PR is merged the stack images will be updated and pushed to docker hub
- Build process will use the stack folder name as the `id`
- Stack images will be tagged with `<id>:<major>`, `<id>:<major>.<minor>`, `<id>:<major.minor.patch>` and `<id>:latest` tags
- When a stack is updated, the build system will identify all stacks that depend on it and create PRs to update the stack.yaml for each dependent stack.
- There is no impact on updating the stack.yaml or image update steps.

### List of all stacks in the repo (index.yaml)
- This should be generated by the build process during the merge of each PR
- Proposed v2 format:
```
apiVersion: v2
generated: 2019-06-24T21:00:00+00:00
stacks: 
- contents of stack.yaml from stack
  id: <folder-name>
  templates:
  - id: <folder>
    url: <location of tar>
  - id: <folder>
    url: <location of tar>
```
- We will keep the old index as is and request users to transition over the the new index over next sprints
- Where should the index be published? (GitHub release?)

### Multiple repos (stable, incubator, experimental)
- We will have an index for each of these repos to allow users to enable/disable them as needed.

### Documenting the release process: 
For the structure of documentation and discussion on the release processes, use https://github.com/appsody/docs/issues/56
