### ISSUE TITLE
Simplify structure of stack.yaml

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/stacks#62]
Stack providers will provide meta information about the stack using `stack.yaml`.  The proposal is to keep it so minimum fields to avoid overhead today. We can always extend them back when needed.

- Proposed format:
```
name: Java MicroProfile® (title on website)
version: 0.2.2
description: Eclipse MicroProfile using AdoptOpenJDK and Maven (description on website)
license: Apache-2.0
maintainers: 
- name:
  email:
  github-id:                  
default-template: <folder-name>
```

- The stack folder name is assumed to be the `id` (when creating repo index)
- Version should be captured using `major.minor.patch` format
- Every time a stack image or template is updated the version in stack.yaml must be updated

There is no impact on updating the stack.yaml today.
